plugins:             [jekyll-paginate]

# Permalinks
permalink:           /:year-:month-:day.html

# Setup
title:               Daily Verse
tagline:             'Several short verses'
description:         'Poems by Ross Bernet. <br> Website by <a href="https://twitter.com/rajadain" target="_blank">@rajadain</a>.'
url:                 https://rossbernet.github.io/
baseurl:             '/daily-verse'
paginate:            5
googleanalytics:     'UA-49051902-3'

github:
  repo:              https://github.com/rossbernet/daily-verse

# About/contact
author:
  name:              Ross Bernet
  url:               https://twitter.com/rosszb
  email:             rossbernet@gmail.com

# Custom vars
version:             1.1.0

theme: jekyll-theme-midnight
