plugins:             [jekyll-paginate]

# Permalinks
permalink:           /:year-:month-:day.html

# Setup
title:               Daily Verse
tagline:             'a short verse (almost) every day'
description:         'Made by <a href="https://twitter.com/rajadain" target="_blank">@rajadain</a>.'
url:                 https://rajadain.github.io/
baseurl:             '/daily-verse'
paginate:            5
googleanalytics:     'UA-49051902-3'

github:
  repo:              https://github.com/rajadain/daily-verse

# About/contact
author:
  name:              Terence Tuhinanshu
  url:               https://twitter.com/rajadain
  email:             terence@tuhinanshu.com

# Custom vars
version:             1.1.0

theme: jekyll-theme-midnight